[terminal]
shell = { program = "/bin/fish" }

[window]
decorations = "full"
dynamic_padding = true
dynamic_title = true
decorations_theme_variant = "Dark"
opacity = 1.0

[window.dimensions]
columns = 200
lines = 50

[window.padding]
x = 10
y = 10

[scrolling]
history = 10000
multiplier = 3

[font]
size = 10

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[colors]
draw_bold_text_with_bright_colors = true

[colors.primary]
foreground = "#c9c7cd"
background = "#242424"

[colors.cursor]
text = "#757581"
cursor = "#c9c7cd"

[colors.normal]
black = "#27272a"
red = "#f5a191"
green = "#90b99f"
yellow = "#e6b99d"
blue = "#aca1cf"
magenta = "#e29eca"
cyan = "#ea83a5"
white = "#c1c0d4"

[colors.bright]
black = "#353539"
red = "#ffae9f"
green = "#9dc6ac"
yellow = "#f0c5a9"
blue = "#b9aeda"
magenta = "#ecaad6"
cyan = "#f591b2"
white = "#cac9dd"
