[terminal]
shell = { program = "/bin/fish" }

[window]
decorations = "full"
dynamic_padding = true
dynamic_title = true
decorations_theme_variant = "Dark"
opacity = 1.0

[window.dimensions]
columns = 200
lines = 50

[window.padding]
x = 10
y = 10

[scrolling]
history = 10000
multiplier = 3

[font]
size = 10

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[colors]
draw_bold_text_with_bright_colors = true

[colors.primary]
foreground = "#d4bed6"
background = "#242424"

[colors.cursor]
text = "#ffffff"
cursor = "#ddc7a1"

[colors.normal]
black = "#27272a"
red = "#ea6976"
green = "#a9b64d"
yellow = "#d8a755"
blue = "#7daed4"
magenta = "#d38697"
cyan = "#89b4c1"
white = "#d4bed6"

[colors.bright]
black = "#27272a"
red = "#ea6976"
green = "#a9b64d"
yellow = "#d8a755"
blue = "#7daed4"
magenta = "#d38697"
cyan = "#89b4c1"
white = "#d4bed6"
