general.live_config_reload = true
terminal.shell.program = "nu"

[window]
decorations = "None"
dynamic_padding = true
dynamic_title = true
decorations_theme_variant = "Dark"
opacity = 1

[window.dimensions]
columns = 200
lines = 50

[window.padding]
x = 10
y = 10

[scrolling]
history = 10000
multiplier = 3

#=============================================================================
# font
#=============================================================================

[font]
size = 10

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

#=============================================================================
# colors
#=============================================================================

# black = "#000000"
# chaotica = "#101010"
# deepspace = "#1b1b1b"
# space = "#2a2a2d"
# lacquer = "#3e3e3e"
# darkgrey = "#505050"
# grey = "#808080"
# silver = "#a6a6a6"
# snow = "#f0f0f0"
# white = "#ffffff"

# blush = "#e78284"
# jade = "#90b99f"
# earl = "#b59efc"
# sky = "#99bbe0"
# myrtle = "#e29eca"
# maple = "#e5c890"

[colors]
draw_bold_text_with_bright_colors = true

[colors.primary]
background = "#101010"
foreground = "#a6a6a6"
dim_foreground = "#CDD6F4"
bright_foreground = "#CDD6F4"

[colors.cursor]
text = "#000000"
cursor = "#b59efc"

[colors.vi_mode_cursor]
text = "#1E1E2E"
cursor = "#B4BEFE"

[colors.search.matches]
foreground = "#1E1E2E"
background = "#A6ADC8"

[colors.search.focused_match]
foreground = "#1E1E2E"
background = "#A6E3A1"

[colors.footer_bar]
foreground = "#1E1E2E"
background = "#A6ADC8"

[colors.hints.start]
foreground = "#1E1E2E"
background = "#F9E2AF"

[colors.hints.end]
foreground = "#1E1E2E"
background = "#A6ADC8"

[colors.selection]
text = "#1E1E2E"
background = "#F5E0DC"

[colors.normal]
black   = "#000000"
red     = "#e78284"
green   = "#90b99f"
yellow  = "#e5c890"
blue    = "#f0f0f0"
magenta = "#b59efc"
cyan    = "#a6a6a6"
white   = "#a6a6a6"

[colors.bright]
black   = "#505050"
red     = "#e78284"
green   = "#90b99f"
yellow  = "#e5c890"
blue    = "#f0f0f0"
magenta = "#b59efc"
cyan    = "#a6a6a6"
white   = "#f0f0f0"

[colors.dim]
black = "#45475A"
red = "#F38BA8"
green = "#A6E3A1"
yellow = "#F9E2AF"
blue = "#89B4FA"
magenta = "#F5C2E7"
cyan = "#94E2D5"
white = "#BAC2DE"

[[colors.indexed_colors]]
index = 16
color = "#FAB387"

[[colors.indexed_colors]]
index = 17
color = "#F5E0DC"

#=============================================================================
# keybinds
#=============================================================================

[keyboard]
bindings = [
  { key = "F11", action = "ToggleFullscreen" }
]

#=============================================================================
# misc
#=============================================================================

[[hints.enabled]]
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"
hyperlinks = true
command = "xdg-open"
post_processing = true
binding = { key = "T", mods = "Control|Shift" }
mouse = { enabled = true, mods = "None" }

[[hints.enabled]]
regex = "[0-9a-f]{12,128}|[a-f0-9]{7,8}"
action = "Copy"
binding = { key = "H", mods = "Control|Shift" }
