format = """
$directory$git_branch$git_state$git_status$git_commit$fill$cmd_duration$line_break$character
"""

[line_break]
disabled = false

add_newline = true;
command_timeout = 1000;

[fill]
symbol = " ";

[directory]
style = "bold blue"
read_only = ""
truncation_length = 4
truncate_to_repo = false

[character]
success_symbol = "[❯](purple)"
error_symbol = "[❯](red)"
vicmd_symbol = "[❮](green)"
disabled = false

[git_branch]
symbol = ""
style = "bright-black"
format = "[$symbol $branch]($style) "

[git_status]
format = "[$all_status$ahead_behind]($style)"
style = "cyan"

[git_commit]
commit_hash_length = 4

[cmd_duration]
format = "[$duration]($style)"
style = "yellow"

[package]
disabled = true

[rust]
disabled = true
