let settings = {
  "/org/gnome/shell/favorite-apps": "['']",
  "/org/gnome/shell/extensions/blur-my-shell/sigma": "30",
  "/org/gtk/settings/file-chooser/clock-format": "'12h'",
  "/org/gtk/settings/file-chooser/show-hidden": "true",
  "/org/gnome/desktop/interface/clock-format": "'12h'",
  "/org/gnome/desktop/interface/clock-show-seconds": "true",
  "/org/gnome/desktop/interface/clock-show-weekday": "true",
  "/org/gnome/desktop/interface/enable-animations": "false",
  "/org/gnome/desktop/interface/show-battery-percentage": "true",
  "/org/gnome/desktop/interface/document-font-name": "'Inter 10'",
  "/org/gnome/desktop/interface/font-name": "'Inter 10'",
  "/org/gnome/desktop/interface/monospace-font-name": "'MapleMonoNormalNLNF 10'",
  "/org/gnome/desktop/interface/titlebar-font": "'Inter Bold 11'",
  "/org/gnome/desktop/interface/text-scaling-factor": "0.94999999999999996",
  "/org/gnome/desktop/interface/accent-color": "'red'",
  "/org/gnome/desktop/wm/preferences/num-workspaces": "10",
  "/org/gnome/desktop/wm/keybindings/move-to-center": "['<Super>c']",
  "/org/gnome/desktop/wm/keybindings/close": "['<Super>q']",
  "/org/gnome/desktop/wm/keybindings/panel-run-dialog": "['<Super>k']",
  "/org/gnome/desktop/search-providers/disabled": "['org.gnome.Contacts.desktop', 'org.gnome.Nautilus.desktop', 'org.gnome.Calculator.desktop', 'org.gnome.Calendar.desktop', 'org.gnome.clocks.desktop', 'org.gnome.seahorse.Application.desktop', 'org.gnome.Epiphany.desktop']",
  "/org/gnome/desktop/privacy/remember-recent-files": "false",
  "/org/gnome/desktop/privacy/remove-old-temp-files": "true",
  "/org/gnome/desktop/privacy/remove-old-trash-files": "true",
  "/org/gnome/desktop/privacy/old-files-age": "14",
  "org/gnome/desktop/peripherals/touchpad/tap-to-click": "true",
  "org/gnome/desktop/peripherals/touchpad/disable-while-typing": "true",
  "org/gnome/desktop/peripherals/touchpad/two-finger-scrolling-enabled": "true",
  "org/gnome/desktop/peripherals/touchpad/natural-scroll": "true",
  "org/gnome/desktop/peripherals/mouse/accel-profile": "'adaptive'",
  "/org/gnome/shell/keybindings/switch-to-application-1": "['']",
  "/org/gnome/shell/keybindings/switch-to-application-2": "['']",
  "/org/gnome/shell/keybindings/switch-to-application-3": "['']",
  "/org/gnome/shell/keybindings/switch-to-application-4": "['']",
  "/org/gnome/shell/keybindings/switch-to-application-5": "['']",
  "/org/gnome/shell/keybindings/switch-to-application-6": "['']",
  "/org/gnome/shell/keybindings/switch-to-application-7": "['']",
  "/org/gnome/shell/keybindings/switch-to-application-8": "['']",
  "/org/gnome/shell/keybindings/switch-to-application-9": "['']",
  "/org/gnome/desktop/wm/keybindings/move-to-workspace-1": "['<Super><Shift>1']",
  "/org/gnome/desktop/wm/keybindings/move-to-workspace-2": "['<Super><Shift>2']",
  "/org/gnome/desktop/wm/keybindings/move-to-workspace-3": "['<Super><Shift>3']",
  "/org/gnome/desktop/wm/keybindings/move-to-workspace-4": "['<Super><Shift>4']",
  "/org/gnome/desktop/wm/keybindings/move-to-workspace-5": "['<Super><Shift>5']",
  "/org/gnome/desktop/wm/keybindings/move-to-workspace-6": "['<Super><Shift>6']",
  "/org/gnome/desktop/wm/keybindings/move-to-workspace-7": "['<Super><Shift>7']",
  "/org/gnome/desktop/wm/keybindings/move-to-workspace-8": "['<Super><Shift>8']",
  "/org/gnome/desktop/wm/keybindings/move-to-workspace-9": "['<Super><Shift>9']",
  "/org/gnome/desktop/wm/keybindings/move-to-workspace-10": "['<Super><Shift>0']",
  "/org/gnome/desktop/wm/keybindings/switch-to-workspace-1": "['<Super>1']",
  "/org/gnome/desktop/wm/keybindings/switch-to-workspace-2": "['<Super>2']",
  "/org/gnome/desktop/wm/keybindings/switch-to-workspace-3": "['<Super>3']",
  "/org/gnome/desktop/wm/keybindings/switch-to-workspace-4": "['<Super>4']",
  "/org/gnome/desktop/wm/keybindings/switch-to-workspace-5": "['<Super>5']",
  "/org/gnome/desktop/wm/keybindings/switch-to-workspace-6": "['<Super>6']",
  "/org/gnome/desktop/wm/keybindings/switch-to-workspace-7": "['<Super>7']",
  "/org/gnome/desktop/wm/keybindings/switch-to-workspace-8": "['<Super>8']",
  "/org/gnome/desktop/wm/keybindings/switch-to-workspace-9": "['<Super>9']",
  "/org/gnome/desktop/wm/keybindings/switch-to-workspace-10": "['<Super>0']",
  "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings": "['/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/', '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/']",
  "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/name": "'Open Alacritty'",
  "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/command": "'alacritty'",
  "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/binding": "'<Super>t'",
  "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/name": "'Open Nautilus'",
  "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/command": "'nautilus'",
  "/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/binding": "'<Super>e'",
}

for $it in ($settings | transpose key value) {
  dconf write $it.key $it.value
}
