# Theme: Gruvbox Material Medium Dark

"attribute" = { fg = "blue", modifiers = ["italic"] }

"keyword" = "blue"
"keyword.control.conditional" = { fg = "blue", modifiers = ["italic"] }
"keyword.directive" = "magenta"

"namespace" = { fg = "cyan", modifiers = ["italic"] }

"punctuation" = "gray06"
"punctuation.delimiter" = "gray06"

"operator" = "yellow"
"special" = "yellow"

"variable" = "fg"
"variable.builtin" = "bright_blue"
"variable.parameter" = "cyan"
"variable.other.member" = "white"

"type" = "bright_blue"
"type.builtin" = "magenta"
"type.enum.variant" = "magenta"

"constructor" = "yellow"

"function" = "white"
"function.macro" = "bright_cyan"
"function.builtin" = "bright_blue"

"tag" = "cyan"
"comment" = { fg = "gray05", modifiers = ["italic"] }

"string" = "green"
"string.regexp" = "green"
"string.special" = "yellow"

"constant" = "cyan"
"constant.builtin" = "yellow"
"constant.numeric" = "magenta"
"constant.character.escape" = "cyan"

"label" = "yellow"

"markup.heading.marker" = { fg = "gray06" }
"markup.heading" = { fg = "bright_blue", modifiers = ["bold"] }
"markup.list" = "gray06"
"markup.bold" = { modifiers = ["bold"] }
"markup.italic" = { modifiers = ["italic"] }
"markup.strikethrough" = { modifiers = ["crossed_out"] }
"markup.link.url" = { fg = "green", modifiers = ["underlined"] }
"markup.link.text" = { fg = "blue", modifiers = ["italic"] }
"markup.raw" = "yellow"

"diff.plus" = "bright_green"
"diff.minus" = "bright_red"
"diff.delta" = "bright_blue"

"ui.background" = { bg = "#282828" }
"ui.background.separator" = { fg = "#d4be98" }

"ui.linenr" = { fg = "#7c6f64" }
"ui.linenr.selected" = { fg = "#d4be98" }

"ui.statusline" = { fg = "#d4be98", bg = "#3c3836" }
"ui.statusline.inactive" = { fg = "#d4be98", bg = "#3c3836", modifiers = ["dim"] }
"ui.statusline.normal" = { fg = "#282828", bg = "#89b482", modifiers = ["bold"] }
"ui.statusline.insert" = { fg = "#282828", bg = "#7daea3", modifiers = ["bold"] }
"ui.statusline.select" = { fg = "#282828", bg = "#d3869b", modifiers = ["bold"] }

"ui.popup" = { bg = "#3c3836" }
"ui.window" = { fg = "#7c6f64" }
"ui.help" = { bg = "#3c3836", fg = "#d4be98" }

"ui.text" = { fg = "#d4be98" }
"ui.text.focus" = { fg = "#d4be98" }

"ui.virtual" = { fg = "#7c6f64" }
"ui.virtual.ruler" = { bg ="#7c6f64" }
"ui.virtual.indent-guide" = { fg = "#7c6f64" }
"ui.virtual.inlay-hint" = { fg = "#7c6f64" }

"ui.selection" = { bg = "#504945" }
"ui.selection.primary" = { bg = "#504945" }

"ui.cursor" = { bg = "#7c6f64" }
"ui.cursor.match" = { fg = "yellow", modifiers = ["bold", "underlined"] }
"ui.cursorline.primary" = { bg = "#3c3836" }

"ui.highlight" = { bg = "#7c6f64" }

"ui.menu" = { fg = "#d4be98", bg = "#3c3836" }
"ui.menu.selected" = { fg = "#d4be98", bg = "#504945" }
"ui.menu.scroll" = { fg = "#7c6f64", bg = "#3c3836" }

"diagnostic.warning" = { underline = { color = "bright_yellow", style = "curl" } }
"diagnostic.error" = { underline = { color = "bright_red", style = "curl" } }
"diagnostic.info" = { underline = { color = "bright_blue", style = "curl" } }
"diagnostic.hint" = { underline = { color = "bright_cyan", style = "curl" } }
"diagnostic.unnecessary" = { modifiers = ["dim"] }
"diagnostic.deprecated" = { modifiers = ["crossed_out"] }

warning = "bright_yellow"
error = "bright_red"
info = "bright_blue"
hint = "bright_cyan"

[palette]
bg = "#282828"
fg = "#d4be98"
bg_dark = "#3c3836"

black = "#3c3836"
bright_black = "#3c3836"

red = "#ea6962"
bright_red = "#ea6962"

green = "#a9b665"
bright_green = "#a9b665"

yellow = "#d8a657"
bright_yellow = "#d8a657"

blue = "#7daea3"
bright_blue = "#7daea3"

magenta = "#d3869b"
bright_magenta = "#d3869b"

cyan = "#89b482"
bright_cyan = "#89b482"

white = "#d4be98"
bright_white = "#d4be98"

gray01 = "#1b1b1d"
gray02 = "#2a2a2d"
gray03 = "#3e3e43"
gray04 = "#57575f"
gray05 = "#757581"
gray06 = "#9998a8"
gray07 = "#c1c0d4"
